test logs configure failed 7.4

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -58,6 +58,16 @@ jobs:
 
          docker build -t img-productos -f ./server/Dockerfile ./server
          docker run --name container-productos -d -p 8000:8000 img-productos
+         docker exec container-productos npm test
+         TEST_EXIT_CODE=$?
+         echo "$TEST_EXIT_CODE"
+         if [ $TEST_EXIT_CODE -ne 0 ]; then
+          echo "Los tests fallaron. Deteniendo el flujo de trabajo."
+          exit 1  # Terminar el flujo de trabajo con error
+         else
+          echo "Los tests fueron exitosos."
+         fi
+
          
   # build:
   #   name: DEPLOY
