test logs configure passed

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -88,18 +88,15 @@ jobs:
  
       - name: Check test results
         run: |
-          if [ "${{ env.exit_code }}" -ne 0 ]; then
-            #if docker ps -a --format '{{.Names}}' | grep -q 'container-productos'; then
-              docker rm -f container-productos
-            fi
-            echo "❌ Tests failed. Stopping workflow."
-            exit 1
-          else
-            if docker ps -a --format '{{.Names}}' | grep -q 'container-productos'; then
-              docker rm -f container-productos
-            fi
+          if [ "${{ env.exit_code }}" -eq 0 ]; then
+            docker rm -f container-productos
             docker run --name container-productos -d -p 8000:8000 img-productos
             echo "✅ Tests passed successfully!"
+          else
+            d
+            docker rm -f container-productos
+            echo "❌ Tests failed. Stopping workflow."
+            exit 1
           fi
       # - name: Deploy application
       #   if: success()
